import { Country } from './types';

export const COUNTRIES: Country[] = [
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    taxYear: 'April 6 – April 5',
    filingDeadline: '31 January',
    filingDeadlineMonth: 1,
    filingDeadlineDay: 31,
    cgRates: { basic: 18, higher: 24 },
    aea: 3000,
    aeaLabel: 'Annual Exempt Amount',
    taxSystem: 'Section 104 Share Pooling',
    notes: 'Same-day rule and 30-day bed & breakfast rule apply. ISA wrapper is CGT-free.',
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    taxYear: 'January 1 – December 31',
    filingDeadline: '15 April',
    filingDeadlineMonth: 4,
    filingDeadlineDay: 15,
    cgRates: { basic: 0, higher: 20, flat: 15 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'FIFO / Specific Identification',
    notes: 'Short-term gains (<1yr) taxed as ordinary income. Long-term: 0%, 15%, or 20% depending on income.',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '31 July',
    filingDeadlineMonth: 7,
    filingDeadlineDay: 31,
    cgRates: { basic: 25, higher: 25, flat: 25 },
    aea: 1000,
    aeaLabel: 'Sparer-Pauschbetrag (Saver\'s Allowance)',
    taxSystem: 'Abgeltungsteuer (Flat Capital Gains Tax)',
    notes: '25% flat rate (plus 5.5% solidarity surcharge). Sparer-Pauschbetrag increased to €1,000 from 2023.',
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: 'May/June (varies)',
    filingDeadlineMonth: 5,
    filingDeadlineDay: 31,
    cgRates: { basic: 30, higher: 30, flat: 30 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'Prélèvement Forfaitaire Unique (PFU)',
    notes: '30% flat tax (12.8% income tax + 17.2% social charges). Can opt for progressive rate if lower.',
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    taxYear: 'January 1 – December 31',
    filingDeadline: '30 April',
    filingDeadlineMonth: 4,
    filingDeadlineDay: 30,
    cgRates: { basic: 50, higher: 50 },
    aea: 0,
    aeaLabel: 'No Annual Exemption (50% Inclusion Rate)',
    taxSystem: 'Marginal Rate on 50% of Gains',
    notes: '50% of capital gains included in income, taxed at marginal rate (federal + provincial).',
  },
  {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencySymbol: 'A$',
    taxYear: 'July 1 – June 30',
    filingDeadline: '31 October',
    filingDeadlineMonth: 10,
    filingDeadlineDay: 31,
    cgRates: { basic: 50, higher: 45 },
    aea: 0,
    aeaLabel: 'No Annual Exemption (50% Discount if >1yr)',
    taxSystem: 'Marginal Rate with 50% CGT Discount',
    notes: 'Assets held >12 months qualify for 50% CGT discount. Taxed at individual marginal rate.',
  },
  {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '31 October',
    filingDeadlineMonth: 10,
    filingDeadlineDay: 31,
    cgRates: { basic: 33, higher: 33, flat: 33 },
    aea: 1270,
    aeaLabel: 'Annual Exempt Amount',
    taxSystem: 'CGT at flat rate',
    notes: '33% flat CGT rate. €1,270 annual exempt amount. Returns filed via Revenue Online Service (ROS).',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '1 May',
    filingDeadlineMonth: 5,
    filingDeadlineDay: 1,
    cgRates: { basic: 36, higher: 36, flat: 36 },
    aea: 57000,
    aeaLabel: 'Heffingsvrij vermogen (Tax-Free Threshold)',
    taxSystem: 'Box 3 – Deemed Return on Wealth',
    notes: 'Box 3 taxes deemed return on net wealth above €57,000 at 36%. Actual gains not separately taxed.',
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '30 June',
    filingDeadlineMonth: 6,
    filingDeadlineDay: 30,
    cgRates: { basic: 19, higher: 28 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'Tiered Savings Tax (Base del Ahorro)',
    notes: '19% up to €6,000; 21% €6,000–€50,000; 23% €50,000–€200,000; 27% €200,000–€300,000; 28% >€300,000.',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '30 November',
    filingDeadlineMonth: 11,
    filingDeadlineDay: 30,
    cgRates: { basic: 26, higher: 26, flat: 26 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'Imposta Sostitutiva (Substitute Tax)',
    notes: '26% flat tax on capital gains. Managed accounts (gestito) allow annual offsetting of losses.',
  },
  {
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    currency: 'EUR',
    currencySymbol: '€',
    taxYear: 'January 1 – December 31',
    filingDeadline: '30 June',
    filingDeadlineMonth: 6,
    filingDeadlineDay: 30,
    cgRates: { basic: 28, higher: 28, flat: 28 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'Flat Rate or Marginal Rate (taxpayer choice)',
    notes: '28% flat rate on capital gains, or can opt to aggregate with income for marginal rate. NHR regime may apply.',
  },
  {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    currency: 'SEK',
    currencySymbol: 'kr',
    taxYear: 'January 1 – December 31',
    filingDeadline: '2 May',
    filingDeadlineMonth: 5,
    filingDeadlineDay: 2,
    cgRates: { basic: 30, higher: 30, flat: 30 },
    aea: 0,
    aeaLabel: 'No Annual Exemption',
    taxSystem: 'Kapitalinkomst (Capital Income Tax)',
    notes: '30% flat tax on capital gains (Kapitalvinstskatt). ISK (Investeringssparkonto) is a tax-advantaged wrapper.',
  },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // UK

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
